name: 4dgs
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10.11
  - pip=23.3.1
  - pytorch=2.5.0
  - pytorch-cuda=11.8
  - torchaudio=2.5.0
  - torchvision=0.20.0
  - plyfile=0.8.1
  - colmap
  - pip:
    - opencv-python
    - numpy
    - pyyaml
    - tqdm==4.66.1
    - torchmetrics==1.2.0
    - imagesize==1.4.1
    - kornia==0.7.0
    - omegaconf==2.3.0
    - ./simple-knn
    - ./diff-gaussian-rasterization
    - ./pointops2
